# Generated by Django 5.2.6 on 2025-12-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_booking_unique_together_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
